spring:
  datasource:
    driver-class-name: org.h2.Driver
    username:
    password:
    url: jdbc:h2:mem:ecommerce_db

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true # This run after the datasource is initialized

  # Required
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  h2.console.enabled: true
  jackson.property-naming-strategy: SNAKE_CASE

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:c0c1f1d0cfada878fe48dd84f30d0b7372c11ffc715db4d96aef3ad667ece0dc}
      access-token.expiration: ${JWT_EXPIRATION_TIME:86400000} # 1 day
      refresh-token.expiration: ${JWT_REFRESH_EXPIRATION_TIME:604800000} # 7 days