services:
  mini-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mini-api
    ports:
      - "8080:8080" # host:container (container default port: 8080)
    environment:
      JWT_SECRET: c0c1f1d0cfada878fe48dd84f30d0b7372c11ffc715db4d96aef3ad667ece0dc
      JWT_EXPIRATION_TIME: 86400000
      JWT_REFRESH_EXPIRATION_TIME: 604800000